// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies this PackageInspection into out.
func (in *PackageInspection) DeepCopyInto(out *PackageInspection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates an independent PackageInspection copy.
func (in *PackageInspection) DeepCopy() *PackageInspection {
	if in == nil {
		return nil
	}
	out := new(PackageInspection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a runtime.Object copy.
func (in *PackageInspection) DeepCopyObject() runtime.Object {
	if copy := in.DeepCopy(); copy != nil {
		return copy
	}
	return nil
}

// DeepCopyInto copies this PackageInspectionList into out.
func (in *PackageInspectionList) DeepCopyInto(out *PackageInspectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]PackageInspection, len(in.Items))
		for index := range in.Items {
			in.Items[index].DeepCopyInto(&out.Items[index])
		}
	}
}

// DeepCopy creates an independent PackageInspectionList copy.
func (in *PackageInspectionList) DeepCopy() *PackageInspectionList {
	if in == nil {
		return nil
	}
	out := new(PackageInspectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject creates a runtime.Object list copy.
func (in *PackageInspectionList) DeepCopyObject() runtime.Object {
	if copy := in.DeepCopy(); copy != nil {
		return copy
	}
	return nil
}

// DeepCopyInto copies this status and all reference slices into out.
func (in *PackageInspectionStatus) DeepCopyInto(out *PackageInspectionStatus) {
	*out = *in
	if in.Report != nil {
		out.Report = new(ReportReference)
		*out.Report = *in.Report
	}
	if in.Risk != nil {
		out.Risk = new(RiskSummary)
		*out.Risk = *in.Risk
		if in.Risk.FindingIDs != nil {
			out.Risk.FindingIDs = append([]string(nil), in.Risk.FindingIDs...)
		}
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		copy(out.Conditions, in.Conditions)
	}
}
